### ISSUE TITLE
Bailout gracefully if the servo can't be initialised

### ISSUE THREAD

**Issue by madpilot** [amberelectric/amber-work-experience#6]
This project is kind of useless if we can't initialise the servo.

If it does fail, flag an error state, and just flash an LED in the loop, rather than trying to hit the API

**Comment by ryftjet** [comment]
Broadening the scope of this issue to making the LED a status LED and updating the `Serial.println()` statements.

To do:
- [x] Devise an error message and status LED scheme
- [x] Remove existing calls to `Serial.println()` and `pixels.setPixelColor()`
- [x] Update the code to follow this
- [x] Make verbosity modes
- [x] Document the scheme in the README

**Comment by ryftjet** [comment]
Error scheme:
Status | LED Colour | Print Statement | Level
-- | -- | -- | --
Connecting to Wi-Fi | Yellow | Connecting to Wi-Fi… | Info
Setting Clock | Green | Setting time… | Info
Fetching Descriptor | Cyan | Fetching descriptor… | Info
Fetching Debug Descriptor | Blue | Fetching descriptor from debug server… | Info
Moving Servo | Purple | Updating servo… | Debug
Idle | White | Done! | Info
**Errors** | **Red-...** |  
Could not connect to Wi-Fi | Red-Red | Could not connect to Wi-Fi | Warning
Could not connect to the API | Red-Yellow-Red | Could not connect to API | Error
Could not configure API | Red-Yellow-Yellow | Could not configure API | Error
API timed out | Red-Yellow-Green | API connection timed out | Error
API gave invalid response | Red-Yellow-Cyan | API returned invalid response | Error
HTTP status code error | Red-Green-Red | API returned error code: [CODE] | Error
HTTP could not skip headers | Red-Green-Yellow | Could not skip HTTP headers: [CODE] | Error
Could not parse JSON | Red-Cyan-Red | Could not parse returned JSON | Error
Could not find general channel | Red-Cyan-Yellow | Could not find general channel in JSON | Error
Servo could not start | Red-Blue | Could not start servo | Fatal
Debug API not provided | Red-Purple | Debug API URL not provided | Warning

**Comment by madpilot** [comment]
LGTM
