### ISSUE TITLE
Debug API

### ISSUE THREAD

**Issue by ryftjet** [amberelectric/amber-work-experience#7]
It's really hard to test different cases efficiently with the Amber API. There should be a simple Python API you can run locally to manually set the price descriptor, and a debug mode in the ESP32 code to point to it rather than the Amber API.

- [x] Make Python API
- [x] Make debug mode for ESP32

**Comment by madpilot** [comment]
Protip. Python has a built in webserver that will serve up static files.

```
mkdir sites/$SITE_ID/prices
curl -H "Authorization: Bearer $API_KEY https://api.amber.com.au/sites/$SITE_ID/prices/current > sites/$SITE_ID/prices/current
python3 -m http.server
```

Then you can point to `$IP_ADDRESS:8000/sites/$SITE_ID/prices/current` and you haven't had to write any code. You just change the descriptor value in the JSON file that lives in the `sites/$SITE_ID/prices/current` file

**Comment by ryftjet** [comment]
Thank you!!
